# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSetTime():
  def setup_method(self, method):
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.add_argument("--private-window")
    self.driver = webdriver.Firefox(options=firefox_options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_setTime(self):
    # Test name: test_setTime
    # Step # | name | target | value
    # 1 | open | https://school.moodledemo.net/ | 
    self.driver.get("https://school.moodledemo.net/")
    # 2 | click | css=.login > a | 
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    # 3 | type | id=username | teacher
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    # 4 | type | id=password | moodle
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    # 5 | click | id=loginbtn | 
    self.driver.find_element(By.ID, "loginbtn").click()
    # 6 | waitForElementPresent | css=.card:nth-child(9) .card-img | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".card:nth-child(9) .card-img")))
    # 7 | runScript | window.scrollTo(0,0.5) | 30000
    self.driver.execute_script("window.scrollTo(0,0.5)")
    # 8 | click | css=.card:nth-child(9) .card-img | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(9) .card-img").click()
    # 9 | click | name=setmode | 
    self.driver.find_element(By.NAME, "setmode").click()
    # 10 | waitForElementPresent | css=#coursecontentcollapse0 .activity-add-text | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#coursecontentcollapse0 .activity-add-text")))
    # 11 | click | css=#coursecontentcollapse0 .activity-add-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#coursecontentcollapse0 .activity-add-text").click()
    # 12 | waitForElementPresent | linkText=Assignment | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Assignment")))
    # 13 | click | linkText=Assignment | 
    self.driver.find_element(By.LINK_TEXT, "Assignment").click()
    # 14 | type | id=id_name | Assignment 1
    self.driver.find_element(By.ID, "id_name").send_keys("Assignment 1")


    # 15 | waitForElementVisible | id=id_allowsubmissionsfromdate_enabled | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "id_allowsubmissionsfromdate_enabled")))
    # 16 | check | id=id_allowsubmissionsfromdate_enabled | 
    element = self.driver.find_element(By.ID, "id_allowsubmissionsfromdate_enabled")
    if element.is_selected() != True: element.click()
    # 17 | waitForElementEditable | id=id_allowsubmissionsfromdate_day | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "id_allowsubmissionsfromdate_year"))) 
    # 18 | click | id=id_allowsubmissionsfromdate_year | 
    self.driver.find_element(By.ID, "id_allowsubmissionsfromdate_year").click()
    # 19 | select | id=id_allowsubmissionsfromdate_year | label=2022
    self.driver.find_element(By.CSS_SELECTOR, "#id_allowsubmissionsfromdate_year > option:nth-child(123)").click()
   
    # 20 | waitForElementVisible | id=id_duedate_enabled | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "id_duedate_enabled")))
    # 21 | check | id=id_duedate_enabled | 
    element = self.driver.find_element(By.ID, "id_duedate_enabled")
    if element.is_selected() != True: element.click()
    # 22 | waitForElementEditable | id=id_duedate_day | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "id_duedate_year")))
    # 23 | click | id=id_duedate_year | 
    self.driver.find_element(By.ID, "id_duedate_year").click()
    # 24 | select | id=id_cutoffdate_year | label=2023
    self.driver.find_element(By.CSS_SELECTOR, "#id_duedate_year > option:nth-child(124)").click()

    # 25 | waitForElementVisible | id=id_cutoffdate_enabled | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "id_cutoffdate_enabled")))
    # 26 | check | id=id_cutoffdate_enabled | 
    element = self.driver.find_element(By.ID, "id_cutoffdate_enabled")
    if element.is_selected() != True: element.click()
    # 27 | waitForElementEditable | id=id_cutoffdate_day | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "id_cutoffdate_year")))
    # 28 | click | id=id_cutoffdate_year | 
    self.driver.find_element(By.ID, "id_cutoffdate_year").click()
    # 29 | select | id=id_cutoffdate_year | label=2024
    self.driver.find_element(By.CSS_SELECTOR, "#id_cutoffdate_year > option:nth-child(125)").click()
    
    # 30 | waitForElementVisible | id=id_gradingduedate_enabled | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "id_gradingduedate_enabled")))
    # 31 | check | id=id_gradingduedate_enabled | 
    element = self.driver.find_element(By.ID, "id_gradingduedate_enabled")
    if element.is_selected() != True: element.click()
    # 32 | waitForElementEditable | id=id_gradingduedate_day | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "id_gradingduedate_year")))
    # 33 | click | id=id_gradingduedate_year | 
    self.driver.find_element(By.ID, "id_gradingduedate_year").click()
    # 34 | select | id=id_gradingduedate_year | label=2025
    self.driver.find_element(By.CSS_SELECTOR, "#id_gradingduedate_year > option:nth-child(126)").click()

    # 35 | click | id=id_submitbutton | 
    self.driver.find_element(By.ID, "id_submitbutton").click()

    # 36 | assertElementNotPresent 
    elements = self.driver.find_elements(By.ID, "id_error_duedate")
    assert len(elements) == 0
    elements = self.driver.find_elements(By.ID, "id_error_cutoffdate")
    assert len(elements) == 0
    elements = self.driver.find_elements(By.ID, "id_error_gradingduedate")
    assert len(elements) == 0

    # 37 | click | id=user-menu-toggle | 
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    # 38 | waitForElementVisible | css=#carousel-item-main > .dropdown-item:nth-child(12) | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#carousel-item-main > .dropdown-item:nth-child(12)")))
    # 39 | click | css=#carousel-item-main > .dropdown-item:nth-child(12) | 
    self.driver.find_element(By.CSS_SELECTOR, "#carousel-item-main > .dropdown-item:nth-child(12)").click()
  
if __name__ == "__main__":
  pytest.main()