# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEmptyName():
  def setup_method(self, method):
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.add_argument("--private-window")
    self.driver = webdriver.Firefox(options=firefox_options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_emptyName(self):
    # Test name: test_emptyName
    # Step # | name | target | value
    # 1 | open | https://school.moodledemo.net/ | 
    self.driver.get("https://school.moodledemo.net/")
    # 2 | click | css=.login > a | 
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    # 3 | type | id=username | teacher
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    # 4 | type | id=password | moodle
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    # 5 | click | id=loginbtn | 
    self.driver.find_element(By.ID, "loginbtn").click()
    # 6 | waitForElementPresent | css=.card:nth-child(9) .card-img | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".card:nth-child(9) .card-img")))
    # 7 | runScript | window.scrollTo(0,0.5) | 30000
    self.driver.execute_script("window.scrollTo(0,0.5)")
    # 8 | click | css=.card:nth-child(9) .card-img | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(9) .card-img").click()
    # 9 | click | name=setmode | 
    self.driver.find_element(By.NAME, "setmode").click()
    # 10 | waitForElementPresent | css=#coursecontentcollapse0 .activity-add-text | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#coursecontentcollapse0 .activity-add-text")))
    # 11 | click | css=#coursecontentcollapse0 .activity-add-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#coursecontentcollapse0 .activity-add-text").click()
    # 12 | waitForElementPresent | linkText=Assignment | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Assignment")))
    # 13 | click | linkText=Assignment | 
    self.driver.find_element(By.LINK_TEXT, "Assignment").click()
    # 14 | click | id=id_submitbutton | 
    self.driver.find_element(By.ID, "id_submitbutton").click()

    # 15 | assertElementPresent | id=id_error_name | 
    elements = self.driver.find_elements(By.ID, "id_error_name")
    assert len(elements) > 0

    # 16 | click | id=user-menu-toggle | 
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    # 17 | waitForElementVisible | css=#carousel-item-main > .dropdown-item:nth-child(12) | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#carousel-item-main > .dropdown-item:nth-child(12)")))
    # 18 | click | css=#carousel-item-main > .dropdown-item:nth-child(12) | 
    self.driver.find_element(By.CSS_SELECTOR, "#carousel-item-main > .dropdown-item:nth-child(12)").click()
  
if __name__ == "__main__":
  pytest.main()