# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddfileresource():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addfilewithoutselectingfile(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1200, 1006)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("test")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.LINK_TEXT, "My courses").click()
    self.driver.find_element(By.CSS_SELECTOR, ".multiline > span:nth-child(2)").click()
    self.driver.find_element(By.NAME, "setmode").click()
    self.driver.find_element(By.CSS_SELECTOR, ".activity-add-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#all-5 .option:nth-child(7) .optionname").click()
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Test")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.ID, "tinymce")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "id_submitbutton2").click()
    assert self.driver.find_element(By.ID, "id_error_files").text == "Required"
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
  def test_addfileresource(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1200, 1006)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("test")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.LINK_TEXT, "My courses").click()
    self.driver.find_element(By.CSS_SELECTOR, ".multiline > span:nth-child(2)").click()
    self.driver.find_element(By.NAME, "setmode").click()
    self.driver.find_element(By.CSS_SELECTOR, ".activity-add-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#all-5 .option:nth-child(7) .optionname").click()
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Test")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.ID, "tinymce")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-file-o").click()
    self.driver.find_element(By.NAME, "repo_upload_file").send_keys("/Users/nhanlenguyen/Downloads/test.txt")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Upload this file\')]").click()
    self.driver.find_element(By.ID, "id_submitbutton2").click()
    self.driver.find_element(By.NAME, "setmode").click()
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.ID, "page").click()
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
  def test_addfilewithtoolongname(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1200, 1006)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("test")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.LINK_TEXT, "My courses").click()
    self.driver.find_element(By.CSS_SELECTOR, ".multiline > span:nth-child(2)").click()
    self.driver.find_element(By.NAME, "setmode").click()
    self.driver.find_element(By.CSS_SELECTOR, ".activity-add-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#all-5 .option:nth-child(7) .optionname").click()
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("\\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in rutrum erat. Integer commodo est ut scelerisque semper. In consectetur, quam non eleifend cursus, risus orci fringilla augue, non finibus libero dui ac libero. Praesent sagittis magna sit amet porta feugiat. Suspendisse non tincidunt nunc. Maecenas pulvinar eleifend pellentesque. Mauris sit amet odio sed quam feugiat mattis. Fusce gravida cursus faucibus. Aliquam in nibh non nibh pellentesque feugiat non nec massa.\\n\\nVivamus imperdiet sagittis ex, at euismod diam maximus nec. Morbi dignissim tincidunt felis, non tincidunt tellus vehicula id. Nulla quis euismod metus, quis sollicitudin mi. Duis vel imperdiet turpis, eget molestie lectus. Quisque pretium vehicula lacinia. Cras enim dui, accumsan eget suscipit at, iaculis at orci. In purus massa, commodo et quam a, venenatis blandit augue. Sed volutpat erat vitae felis aliquam tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer eu erat ligula.\\n\\nProin felis velit, accumsan eu eros et, blandit placerat felis. Donec cursus nisl at ex vestibulum imperdiet. Nullam ut lorem dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut a eleifend ante. Cras egestas, orci sit amet congue mollis, est nibh dignissim orci, sed suscipit purus neque quis arcu. Fusce eros purus, venenatis nec mollis vitae, rutrum et quam. Proin enim metus, dignissim sed augue a, hendrerit pretium urna. Pellentesque luctus, sem non pellentesque tempor, dolor turpis vehicula magna, et bibendum tortor ligula eu libero. Cras volutpat malesuada metus, sit amet tincidunt augue volutpat in. Sed ut rutrum arcu, at mattis orci. Cras viverra leo nec erat condimentum, et pharetra enim tincidunt. Nam.")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.ID, "tinymce")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-file-o").click()
    self.driver.find_element(By.NAME, "repo_upload_file").send_keys("/Users/nhanlenguyen/Downloads/test.txt")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Upload this file\')]").click()
    self.driver.find_element(By.ID, "id_submitbutton2").click()
    assert self.driver.find_element(By.ID, "id_error_name").text == "- Maximum of 255 characters"
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
  def test_addfiletoolarge(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1200, 1006)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("test")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.LINK_TEXT, "My courses").click()
    self.driver.find_element(By.CSS_SELECTOR, ".multiline > span:nth-child(2)").click()
    self.driver.find_element(By.NAME, "setmode").click()
    self.driver.find_element(By.CSS_SELECTOR, ".activity-add-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#all-5 .option:nth-child(7) .optionname").click()
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Test")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.ID, "tinymce")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-file-o").click()
    self.driver.find_element(By.NAME, "repo_upload_file").send_keys("/Users/nhanlenguyen/Downloads/test500MB.txt")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Upload this file\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.XPATH, "//h3[contains(.,\'File picker\')]")))
    self.driver.find_element(By.XPATH, "//button[contains(@class, \"closebutton\")]").click()
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
